### ISSUE TITLE
Python script doesn't see the Go Direct device

### ISSUE THREAD

**Issue by elenfoxx** [VernierST/godirect-py#25]
Please help! I'm trying to connect one of our SpectroVis Plus devices to my RasPi for the upcoming lab, but the Python script says "number of usb devices found = 0". 
![image](https://user-images.githubusercontent.com/61261563/131886621-5dd1744f-24a6-49ea-a44c-5ebbef1a8cb5.png)

I did pip install godirect[USB] and added the udev rule. I checked, and the rule is in fact there (unless I have to make changes to the rule for it to work?)
![image](https://user-images.githubusercontent.com/61261563/131888401-e12a9b74-bfe3-41de-bdf4-fad12e96f8b7.png)

I connected and disconnected the device and tried all 4 USB ports, but no luck. I have Raspberry Pi 4, and it is updated to the latest version as of today (Raspbian GNU/Linux 10 (buster)).
![image](https://user-images.githubusercontent.com/61261563/131887958-734fa1d1-b02f-425a-8302-4245979bd2d6.png)

Is there anything else I can do? 
Thank you,

Elena

**Comment by stocktonkincade** [comment]
I am afraid that the SpectoVis Plus is not supported by the godirect-py module. It has a unique command set that makes it stand apart from all of the other Go Direct devices. We do not currently have a solution for this for Python or Raspberry Pi. We apologize that this was not clear in the documentation for these tools.

**Comment by elenfoxx** [comment]
Thank you so much for your reply! Does this mean that Vernier Spectrometer also falls in the category of the devices that aren't supported? 
![image](https://user-images.githubusercontent.com/61261563/131903100-393c7b85-bb79-42c5-8897-05fcf20308cc.png)

**Comment by stocktonkincade** [comment]
Yes, I am afraid so. We will get our documentation updated to avoid this confusion in the future. Thank you.

**Comment by elenfoxx** [comment]
Thank you for clarifying that. Have a wonderful day!
