### ISSUE TITLE
iOS Support for GoDirect

### ISSUE THREAD

**Issue by smsophiemi** [VernierST/godirect-py#29]
I am working on a iOS app that needs to connect to a GoDirect device via Bluetooth, and then collect force data.

However, while I can discover the Bluetooth device and connect to it, I can't select any sensors or collect data. Has anyone else tried developing a iOS app using this library that has Bluetooth capability, or know if the godirect library supports this?

**Comment by sswartley** [comment]
Hello,

There are two libraries that support Go Direct sensors - a Python library and a JavaScript library. The Python library works on Windows 10, macOS, or Linux (including Raspberry Pi) computers. The JavaScript library is implemented using WebBluetooth and WebHID, both of which have limited browser support. Currently, iOS devices are not compatible with this protocol, as described in [this support document](https://www.vernier.com/til/10580). 

All the best,

Sam
